services:
  php:
    image: drupal-testflight:latest
    ports:
      - "80:8080"
    environment:
    # https://serversideup.net/open-source/docker-php/docs/reference/environment-variable-specification
      PHP_MEMORY_LIMIT: "512M"
      PHP_OPCACHE_ENABLE: "1"
      PHP_DISPLAY_ERRORS: “Off"
      PHP_POST_MAX_SIZE: "25M"
