name: Build & Publish Images

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    uses: ./.github/workflows/matrix-generator.yml
    with:
      php_versions: '["8.4"]'
      os_versions: '["trixie"]'
      blueprints: |
        {
          "vmaker": {},
          "builder": {
            "build_args": ["NODE=24"],
            "test_command": "docker run --rm \"$IMAGE\" verify-builder.sh"
          },
          "serversideup-apache-fpm": {},
          "apache": {
            "test_command": "PHP_UPLOAD_MAX_FILESIZE=128M PHP_POST_MAX_SIZE=129M PHP_MAX_EXECUTION_TIME=180 EXPECTED_PHP_SAPI=apache2handler ./test/test-apache-php.sh \"$IMAGE\""
          },
          "apache-fpm": {
            "test_command": "PHP_UPLOAD_MAX_FILESIZE=128M PHP_POST_MAX_SIZE=129M PHP_MAX_EXECUTION_TIME=180 EXPECTED_PHP_SAPI=fpm-fcgi ./test/test-apache-php.sh \"$IMAGE\""
          }
        }

  build:
    needs: prepare
    permissions:
      contents: read

    strategy:
      max-parallel: 4
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}

    uses: alchatti/.github/.github/workflows/docker-build-push.yml@main
    with:
      context: .
      dockerfile: ${{ matrix.context }}/Dockerfile
      platforms: linux/amd64,linux/arm64
      build_args: ${{ matrix.build_args }}
      tags: ${{ matrix.tags }}
      target: ${{ matrix.target }}

      test_command: ${{ matrix.test_command }}
      test_platform: linux/amd64
      test_image_tag: ${{ matrix.test_image_tag }}

      cache_from: type=gha,scope=${{ matrix.variant }}
      cache_to: type=gha,mode=max,scope=${{ matrix.variant }}

    secrets: inherit
