name: Build & Publish Images

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Job 1: Generate the full matrix using target mapping conventions
  prepare:
    uses: ./.github/workflows/matrix-generator.yml
    with:
      php_versions: '["8.3", "8.4"]'
      os_versions: '["bookworm", "trixie"]'
      blueprints: |
        {
          "builder": ["NODE=24"],
          "fpm-apache": [],
          "apache":[]
        }

  # Job 2: Process single and multi-stage builds concurrently
  build:
    needs: prepare
    permissions:
      contents: read
    strategy:
      max-parallel: 4
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
    
    uses: alchatti/.github/.github/workflows/docker-build-push.yml@main
    with:
      context: ${{ matrix.context }}
      dockerfile: ${{ matrix.context }}/Dockerfile
      platforms: linux/amd64,linux/arm64
      build_args: ${{ matrix.build_args }}
      tags: ${{ matrix.tags }}
      target: ${{ matrix.target }}
      # Explicitly pass cache configurations to the backend
      cache_from: type=gha,scope=${{ matrix.context }}-${{ matrix.target }}
      cache_to: type=gha,mode=max,scope=${{ matrix.context }}-${{ matrix.target }}
    secrets: inherit
